version: "3.9"

volumes:
  auth_postgres_data: {}
  auth_postgres_data_backups: {}

services:
  api:
    build: .
    ports:
      - "8014:80"
    environment:
      - ConnectionStrings__PostgreSQLConnection=Server=postgres;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};       

  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - auth_postgres_data_backups:/backups
    env_file:
      - .env