version: "3.9"

volumes:
  auth_postgres_data: {}
  auth_postgres_data_backups: {}

services:
  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - "5430:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - auth_postgres_data_backups:/backups
    env_file:
      - .env